name: 'Setup Node'
description: 'Sets up Node.js for Node-based sources'
inputs:
  node-version:
    description: 'Node.js version to install'
    required: false
    default: '18'
runs:
  using: 'composite'
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Verify Node and NPM
      shell: bash
      run: |
        node --version || true
        npm --version || true
