name: 'Setup Build Tools (by source_dir)'
description: 'Sets up language-specific build tools based on the provided source_dir input.'
inputs:
  source_dir:
    description: 'Source directory name or identifier used to determine language'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Setup Java (if Java source)
      if: contains(inputs.source_dir, 'java')
      uses: ./.github/actions/sources/java
      with:
        java-version: 17
        cache-maven: 'true'

    - name: Setup Node (if Node source)
      if: contains(inputs.source_dir, 'node')
      uses: ./.github/actions/sources/node
      with:
        node-version: 20

    - name: No build tools required
      if: "!contains(inputs.source_dir, 'java') && !contains(inputs.source_dir, 'node')"
      run: |
        echo "No language-specific build tools configured for '${{ inputs.source_dir }}'"
        exit 1
      shell: bash
